#!/bin/bash

# Extract the keys_container top and bottom
head -n 35 app/src/main/res/layout/stitch_keyboard_layout.xml > temp_layout.xml

# Generate the 3 rows
cat << 'INNER_EOF' >> temp_layout.xml
    <LinearLayout android:layout_width="match_parent" android:layout_height="52dp" android:orientation="horizontal" android:weightSum="10" android:layout_marginBottom="6dp" android:gravity="center">
        <TextView android:id="@+id/key_q" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="Q" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_w" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="W" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_e" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="E" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_r" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="R" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_t" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="T" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_y" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="Y" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_u" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="U" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_i" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="I" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_o" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="O" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_p" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="P" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
    </LinearLayout>

    <LinearLayout android:layout_width="match_parent" android:layout_height="52dp" android:orientation="horizontal" android:weightSum="10" android:layout_marginBottom="6dp" android:gravity="center">
        <Space android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="0.5" />
        <TextView android:id="@+id/key_a" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="A" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_s" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="S" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_d" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="D" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_f" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="F" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_g" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="G" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_h" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="H" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_j" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="J" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_k" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="K" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_l" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="L" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <Space android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="0.5" />
    </LinearLayout>

    <LinearLayout android:layout_width="match_parent" android:layout_height="52dp" android:orientation="horizontal" android:weightSum="10" android:layout_marginBottom="6dp" android:gravity="center">
        <TextView android:id="@+id/key_z" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="Z" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_x" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="X" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_c" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="C" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_v" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="V" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_b" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="B" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_n" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="N" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_m" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="M" android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_comma" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="," android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <TextView android:id="@+id/key_period" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:text="." android:textColor="?attr/stitchTextColor" android:textSize="21sp" android:gravity="center" android:background="@drawable/bg_key_circle" android:clickable="true" android:focusable="true" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:fontFamily="sans-serif-light" />
        <FrameLayout android:id="@+id/key_backspace" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:layout_marginHorizontal="2dp" android:layout_marginVertical="2dp" android:background="@drawable/bg_command_pill" android:clickable="true" android:focusable="true">
            <ImageView android:layout_width="22dp" android:layout_height="22dp" android:layout_gravity="center" android:src="@drawable/ic_backspace" android:contentDescription="Delete Key" android:tint="?attr/stitchTextColor" />
        </FrameLayout>
    </LinearLayout>
INNER_EOF

tail -n +78 app/src/main/res/layout/stitch_keyboard_layout.xml >> temp_layout.xml

mv temp_layout.xml app/src/main/res/layout/stitch_keyboard_layout.xml

